cryptids/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('cryptids/', views.cryptids, name = 'cryptids'),
    path('cryptids/<int:cryptid_id>/', views.cryptid_detail, name = 'cryptid_detail'),
    path('cryptids/<int:cryptid_id>/sightings/', views.cryptid_sightings, name = 'cryptid_sightings'),
    path('cryptids/tags/<str:tag>/', views.cryptid_tags, name = 'cryptid_tags'),
    path('locations/', views.locations, name = 'locations'),
    path('locations/<int:location_id>/', views.location_detail, name = 'location_detail'),
    path('locations/<int:location_id>/sightings/', views.location_sightings, name = 'location_sightings'),
    path('sightings/<int:year>/', views.sightings_year, name = 'sightings_year'),
    path('sightings/<int:year>/<int:month>/', views.sightings_year_month, name = 'sightings_year_month'),
    path('sightings/<int:year>/<int:month>/<int:day>/', views.sightings_year_month_day, name = 'sightings_year_month_day'),
    path('sightings/continent/<continent>/', views.sightings_continent, name = 'sightings_continent'),
]

library/models.py
from django.db import models
from taggit.managers import TaggableManager

class Cryptid(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    tags = TaggableManager()
    image = models.ImageField(upload_to = 'library/images', default = 'library/images/default.png')
    def __str__(self):
        return f"{self.name}: {self.description[:40]}..."

class Location(models.Model):
    cryptid = models.ForeignKey(Cryptid, on_delete = models.CASCADE)
    name = models.CharField(max_length=200)
    continent = models.CharField(max_length=16)
    def __str__(self):
        return f"{self.name}"

class Sighting(models.Model):
    cryptid = models.ForeignKey(Cryptid, on_delete = models.CASCADE)
    location = models.ForeignKey(Location, on_delete = models.CASCADE)
    report = models.TextField()
    date = models.DateField()
    def __str__(self):
        return f"{self.date}"

library/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from .models import Cryptid, Location, Sighting
from datetime import date

def index(request):
    return render(request, 'library/index.html')

def cryptids(request):
    context = {'cryptids': Cryptid.objects.all()}
    return render(request, 'library/cryptids.html', context)

def cryptid_detail(request, cryptid_id):
    try:
        context = {'cryptid': Cryptid.objects.get(pk=cryptid_id)
        }
    except Cryptid.DoesNotExist:
        return render(request, 'library/404.html')
    
    return render(request, 'library/cryptid_detail.html', context)

def cryptid_sightings(request, cryptid_id):
    return HttpResponse('Cryptid sightings')

def cryptid_tags(request, tag):
    context = {'cryptids': Cryptid.objects.filter(tags__name__in = [tag])}
    return render(request, 'library/cryptids.html', context)

def locations(request):
    context = {'locations': Location.objects.all()}
    return render(request, 'library/map.html', context)

def location_detail(request, location_id):
    try:
        context = {'location': Location.objects.get(pk=location_id)
        }
    except Location.DoesNotExist:
        return render(request, 'library/404.html')
    
    return render(request, 'library/location_detail.html', context)

def sightings_continent(request, continent):
    context = {
        'continent': continent,
        'sightings': Sighting.objects.filter(location__continent__icontains = continent)}
    return render(request, 'library/continent.html', context)

def location_sightings(request, location_id):
    return HttpResponse('location sightings')

def sightings_year(request, year):
    context = {'sightings': Sighting.objects.filter(date__year = year), 'date': date(year, 1, 1), 'type': 'year'}
    return render(request, 'library/sightings.html', context)
    
def sightings_year_month(request, year, month):
    context = {'sightings': Sighting.objects.filter(date__year = year).filter(date__month = month), 'date': date(year, month, 1), 'type': 'month'}
    return render(request, 'library/sightings.html', context)

def sightings_year_month_day(request, year, month, day):
    context = {'sightings': Sighting.objects.filter(date__year = year).filter(date__month = month).filter(date__day = day),'date': date(year, month, day), 'type': 'day'}
    return render(request, 'library/sightings.html', context)

library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'library/app.css' %}">
    {% block CSS %}
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Major+Mono+Display&display=swap" rel="stylesheet">
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
    {% block icon %}<link rel = "icon" href =  "{% static 'library/decryptid-title.png' %}" type = "image/x-icon">{% endblock %}
</head>
<body>
    {% block navbar %}
{% block navstyle %}<link rel="stylesheet" href="{% static 'library/nav.css' %}">{% endblock %}
<nav>
    <div class="nav-home">
        <a href="{% url 'index' %}">
            <img class="nav-img" src="{% static 'library/decryptid-title.png' %}">
        </a>
    </div>
    <div class="nav-pages">
        <a href="{% url 'cryptids' %}">
            <h1>all cryptids</h1>
        </a>
        <a href="{% url 'locations' %}">
            <h1>cryptid map</h1>
        </a>
    </div>
</nav>
{% endblock %}
    {% block content %}

    {% endblock %}
</body>
</html>

library/templates/library/continent.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %}<link rel="stylesheet" href="{% static 'library/continents.css' %}">{% endblock %}
{% block title %}DeCryptid | {{ continent }}{% endblock %}
{% block content %}

<h1 id="continent-title">{{ continent }}</h1>

{% for sighting in sightings %}
    <!-- <a href = "{% url 'sightings_continent' sighting.id %}"></a> -->
    <div class="continent-sightings">
        <a href = "{% url 'location_detail' sighting.location.id %}"><h1>Location: {{ sighting.location }}</h1></a>
        <a href = "{% url 'cryptid_detail' sighting.cryptid.id %}"><h2>{{ sighting.cryptid.name }}</h2></a>
        <a href = "{% url 'sightings_year' sighting.date.year %}"><h3>{{ sighting.date }}</h3></a>
        <p>{{ sighting.report }}</p>
    </div>
{% empty %}
    <p>No sightings yet</p>
{% endfor %}

{% endblock %}

library/templates/library/cryptid_detail.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %}<link rel="stylesheet" href="{% static 'library/cryptid_detail.css' %}">{% endblock %}
{% block title %}DeCryptid | {{cryptid.name}} {% endblock %}
{% block content %}


<div class ="cryptid_detail_wrapper">
    <h1 class ="title">{{ cryptid.name }}</h1>
    <div class ="cryptid-description">
        <img src = '{{ cryptid.image.url }}' alt= '{{ cryptid.name }}' class = 'cryptid_detail_image'>
        <h2>Description</h2>
        <p>{{ cryptid.description }}</p>
        <div class = 'tags'>
            {% for tag in cryptid.tags.all %}
            <a class = "tag-border" href = "{% url 'cryptid_tags' tag.name %}">
                <h5 class = 'tag-name'>{{ tag.name }}</h5>
            </a>
            {% endfor %}
        </div>
        <br><h2>Known Locations Are:</h2>
        {% for location in cryptid.location_set.all %}
            <a href = "{% url 'location_detail' location.id %}"><h3> {{ location.name }} </h3></a>
        {% endfor %}
        <br><h2>Reported Sightings:</h2>
        {% for sighting in cryptid.sighting_set.all %}
            <a href = "{% url 'sightings_year' sighting.date.year %}"><h2>{{ sighting.date }}</h2></a> 
            <a href = "{% url 'location_detail' sighting.location.id %}"><h2>{{ sighting.location }}</h2></a>
            <p>{{ sighting.report }}</p> 
        {% endfor %}
    </div> 
</div>
<br>

{% endblock %}

library/templates/library/cryptids.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %} <link rel="stylesheet" href="{% static 'library/cryptids.css' %}">{% endblock %}
{% block title %}DeCryptid | Cryptids{% endblock %}z
{% block content %}

<div class = 'cryptids-wrapper'>
{% for cryptid in cryptids %}
    <div class = 'cryptid-item'>
        <a href = "{% url 'cryptid_detail' cryptid.id %}" class = "cryptid-name">
            <h2 class = "cryptid-name">{{ cryptid.name }}</h2>
            <img src = '{{ cryptid.image.url }}' alt = '{{ cryptid.name }}' class = 'cryptid-image'>
            <br>
        </a>
        <div class = 'tags'>
        {% for tag in cryptid.tags.all %}
            <a class = "tag-border" href = "{% url 'cryptid_tags' tag.name %}">
                <h5 class = 'tag-name'>{{ tag.name }}</h5>
            </a>
            {% endfor %}
        </div>
    </div>
    <br>

{% empty %}
    <p>No cryptids</p>
{% endfor %}
</div>

{% endblock %}

library/templates/library/index.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %} <link rel="stylesheet" href="{% static 'library/home.css' %}">{% endblock %}
{% block title %}DeCryptid | Home{% endblock %}
{% block content %}
<div class = "homePage">
    <img class="logo" src="{% static 'library/descryptid.png' %}">
    <h3>All the information, locations, sightings & hairiness of your favourite cryptids!</h3>
</div>
{% endblock %}

library/templates/library/location_detail.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %}
<link rel="stylesheet" href="{% static 'library/location_detail.css' %}">
{% endblock %}
{% block title %}DeCryptid | {{location.name}} {% endblock %}
{% block content %}


<div class ="location-detail-wrapper">
    <h1 class ="location-detail-title">All Cryptid Sightings In {{ location.name }}</h1>
    <div class ="location-description">
        {% for sighting in location.sighting_set.all %}
            <div class="location-card">
                <a href = "{% url 'sightings_year' sighting.date.year %}"><h2> {{ sighting.date }}</h2></a>
                <a href = "{% url 'cryptid_detail' sighting.cryptid.id %}"><h2>{{ sighting.cryptid.name }}</h2></a>
                <img src = '{{ sighting.cryptid.image.url }}' alt= '{{ sighting.cryptid.name }}' class = 'location_detail_image'>
                <p>{{ sighting.report }}</p> 
            </div>
        {% endfor %}
    </div> 
</div>
<br>

{% endblock %}

library/templates/library/map.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %}<link rel="stylesheet" href="{% static 'library/map.css' %}">{% endblock %}
{% block title %}DeCryptid | Cryptid Map{% endblock %}
{% block content %}
<div class="main-map-page">
    <div class="map-header">
        <h1 class="map-title">Map of Sightings</h1>
        <p>Select a continent to see all cryptid sightings reported there!</p>
    </div>
    <div class="map">
        <!-- <img class="world" src="{% static 'library/world-grey.png' %}"> -->
        <a href = "{% url 'sightings_continent' 'Africa' %}">
            <img class="africa" src="{% static 'library/africa-grey.png' %}" title="Africa">
        </a>
        <a href = "{% url 'sightings_continent' 'Europe' %}">
            <img class="europe" src="{% static 'library/europe-grey.png' %}" title="Europe">
        </a>
        <a href = "{% url 'sightings_continent' 'Asia' %}">
            <img class="asia" src="{% static 'library/asia-grey.png' %}" title="Asia">
        </a>
        <a href = "{% url 'sightings_continent' 'North America' %}">
            <img class="northamerica" src="{% static 'library/northamerica-grey.png' %}" title="North America">
        </a>
        <a href = "{% url 'sightings_continent' 'South America' %}">
            <img class="southamerica" src="{% static 'library/southamerica-grey.png' %}" title="South America">
        </a>
        <a href = "{% url 'sightings_continent' 'Australia' %}">
            <img class="australia" src="{% static 'library/australia-grey.png' %}" title="Australia">
        </a>
        <a href = "{% url 'sightings_continent' 'Far Far Away' %}">
            <img class="farfaraway" src="{% static 'library/shrekmap.png' %}" title="Far Far Away">
        </a>
    </div>
</div>

{% endblock %}<!---end body-->

library/templates/library/sightings.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %}<link rel="stylesheet" href="{% static 'library/sightings.css' %}">{% endblock %}
{% block title %}DeCryptid | {{ date.year }} Sightings{% endblock %}
{% block content %}

{% if type == 'year' %}
    <h1 id="year-title">{{ date.year }}</h1>
{% elif type == 'month' %}
    <h1 id="year-title">{{ date|date:'F Y' }}</h1>
{% else %}
    <h1 id="year-title">{{ date|date:'jS F Y' }}</h1>
{% endif %}

{% for sighting in sightings %} 
    <div class="year-sightings">
        <h1>{{ sighting.date }}</h1>
        <a href = "{% url 'location_detail' sighting.location.id %}"><h2>{{ sighting.location }}</h2></a>
        <a href = "{% url 'cryptid_detail' sighting.cryptid.id %}"><h2>{{ sighting.cryptid.name }}</h2></a>
        <p>{{ sighting.report }}</p>
    </div>
{% empty %}
    <p>No sightings for this date</p>
{% endfor %}


{% endblock %}

library/templates/library/tags.html
{% extends 'base.html' %}
{% load static %}
{% block CSS %} {% endblock %}
{% block title %}DeCryptid | Tags{% endblock %}
{% block content %}

<div class = 'cryptids-wrapper'>
    {% for cryptid in cryptids %}
        <div class = 'cryptid-item'>
            <a href = "{% url 'cryptid_detail' cryptid.id %}">
                {{ cryptid.name }}
            <br>
            <img src = '{{ cryptid.image.url }}' alt = '{{ cryptid.name }}' class = 'cryptid-image'>
            <br>
            </a>
            <div class = 'tags'>
            {% for tag in cryptid.tags.all %}
                <h5 class = 'tag-name'>{{ tag.name }}</h5>
            {% endfor %}
            </div>
        </div>
        <br>
    {% empty %}
        <p>No cryptids</p>
    {% endfor %}
    </div>

{% endblock %}